language: rust
rust: stable
dist: xenial

env:
  global:
    - RUST_STACKTRACE=full

matrix:
  include:
    - os: osx
      rust: stable
      env: LINT=false
    - os: linux
      rust: stable
      env: LINT=false
    - os: linux
      rust: stable
      env: LINT=true

before_script:
  - rustc -V
  - cargo -V

script:
  - |
      if [[ "$LINT" == "false" ]]; then
        cargo test --verbose
      else
        rustup component add clippy
        cargo clippy
        cd www/
        npm install
        npm run lint
      fi

notifications:
  email:
    on_success: never
    on_failure: change
