language: rust
rust: stable
dist: xenial

env:
  global:
    - RUST_STACKTRACE=full

matrix:
  include:
    - os: osx
      rust: stable
    - os: linux
      rust: stable

before_script:
  - rustc -V
  - cargo -V

script:
  - cargo test --verbose

notifications:
  email:
    on_success: never
    on_failure: change
