language: rust
rust: stable
dist: xenial

env:
  global:
    - RUST_STACKTRACE=full

matrix:
  include:
    - os: osx
      rust: stable
      env: LINT=false
    - os: linux
      rust: stable
      env: LINT=false
    - os: linux
      rust: stable
      env: LINT=true

install:
  - cargo install wasm-pack

before_script:
  - rustc -V
  - cargo -V
  - wasm-pack --version

script:
  - |
      if [[ "$LINT" == "false" ]]; then
        cargo test --verbose
        wasm-pack build --release
      else
        rustup component add clippy
        cargo clippy
        wasm-pack build
        cd www/
        npm install
        npm run lint
      fi

notifications:
  email:
    on_success: never
    on_failure: change
