//! This module provides WebAssembly support
//!
//! This module is only enabled when target architecture is "wasm32". In Wasm, full-set of
//! world-map-gen library is not available due to restriction of wasm-bindgen. wasm-bindgen does
//! not allow lifetimes and type parameters in structs. Many types are not supported to be serialized
//! into Wasm ABI.
//!
//! This module provides some structs which are suitable for being used by JavaScript through
//! wasm-bindgen. The structs provides only limited features of world-map-gen but primary features
//! are covered.
//!
//! Wasm package can be installed as npm package: https://www.npmjs.com/package/world-map-gen
//!
//! ```javascript
//! import { Generator } from 'world-map-gen';
//!
//! // Generate a new random map generator
//! const gen = Generator.new();
//!
//! // Generate random 200x200 map
//! const board = gen.gen(200, 200);
//!
//! for (let x = 0; x < board.width; x++) {
//!     for (let y = 0; y < board.height; y++) {
//!         // Get cell of specific position
//!         const cell = board.at(x, y);
//!
//!         // Get land kind like Sea, Forest, Mountain, ...
//!         console.log('Kind:', cell.kind, 'at', x, y);
//!
//!         // Get altitude of the cell
//!         console.log('  Altitude:', cell.altitude);
//!
//!         // Get color code of the cell as #rrggbb format
//!         console.log('  Color:', board.land_color(cell.kind));
//!
//!         // Get land legend
//!         console.log(' Legend:', board.land_legend(cell.kind));
//!     }
//! }
//! ```

extern crate rand;
extern crate termcolor2rgb;
extern crate wasm_bindgen;

use self::rand::rngs;
use crate::board;
use crate::gen::RandomBoardGen;
use crate::land::LandKind;
use std::collections::HashMap;
use wasm_bindgen::prelude::*;

/// Represents one cell in board. In contrast to `land::Land`, it only contains its land kind and
/// altitude in order to reduce total memory size.
#[wasm_bindgen]
#[derive(Copy, Clone, PartialEq, Eq)]
pub struct Cell {
    pub kind: LandKind,
    pub altitude: u8,
}

/// Represents one board generated by random map generator.
#[wasm_bindgen]
pub struct Board {
    pub width: usize,
    pub height: usize,
    cells: Vec<Cell>,
    colors: HashMap<LandKind, (u8, u8, u8)>,
}

#[wasm_bindgen]
impl Board {
    /// Returns cell at position (x, y).
    pub fn at(&self, x: usize, y: usize) -> Cell {
        let idx = y * self.width + x;
        self.cells[idx]
    }

    /// Returns color of land as `#rrggbb` format string from land kind.
    pub fn land_color(&self, kind: LandKind) -> String {
        match self.colors.get(&kind) {
            Some((r, g, b)) => format!("#{:02x}{:02x}{:02x}", r, g, b),
            None => "".to_string(),
        }
    }

    /// Returns legend of land as string from land kind.
    pub fn land_legend(&self, kind: LandKind) -> String {
        kind.legend().to_string()
    }
}

impl Board {
    fn from_board(b: board::Board) -> Board {
        use termcolor2rgb::ColorExt;

        let mut cells = Vec::with_capacity(b.width() * b.height());
        let mut colors = HashMap::new();
        for cell in b.iter() {
            cells.push(Cell {
                kind: cell.kind,
                altitude: cell.altitude,
            });
            colors
                .entry(cell.kind)
                .or_insert_with(|| cell.color.fg().map(|c| c.to_rgb()).unwrap_or((0, 0, 0)));
        }

        Board {
            width: b.width(),
            height: b.height(),
            cells,
            colors,
        }
    }
}

/// Represents random map generator. In contrast to `gen::RandomBoardGen`, it only provides limited
/// functionality. It cannot be initialized with specific seed. And map resolution is always detected
/// from its size.
#[wasm_bindgen]
pub struct Generator {
    inner: RandomBoardGen<rngs::ThreadRng>,
}

#[wasm_bindgen]
impl Generator {
    pub fn new() -> Generator {
        Generator {
            inner: RandomBoardGen::default(),
        }
    }

    /// Generates random map board with given width and height. Parameters are in number of cells.
    pub fn gen(&mut self, width: usize, height: usize) -> Board {
        let board = self.inner.gen_auto(width, height);
        Board::from_board(board)
    }
}
